os: linux
dist: trusty

services: docker

language: shell

branches:
  only:
    - master

before_script:
  - env | sort
  - dir="images/${VERSION}/${VARIANT}"
  - export TAG=travis
  - export VCS_REF=`git rev-parse --short HEAD`
  - export BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"`
  - export IMAGE_NAME=docker-etherpad

script:
  - cd "$dir"
  # Test containers build
  - docker-compose -f docker-compose.yml build
  - docker images
  # Test containers run
  - travis_retry docker-compose -f docker-compose.yml up -d etherpad_db && sleep 60
  - docker-compose -f docker-compose.yml ps
  - docker-compose -f docker-compose.yml logs "etherpad_db"
  - docker-compose -f docker-compose.yml ps "etherpad_db" | grep "Up"
  - travis_retry docker-compose -f docker-compose.yml up -d && sleep 30
  - docker-compose -f docker-compose.yml ps
  - docker-compose -f docker-compose.yml logs "etherpad"
  - docker-compose -f docker-compose.yml ps "etherpad" | grep "Up"
  - echo 'Wait until containers init and tests are over' && sleep 60
  - docker-compose -f docker-compose.yml logs "sut"
  - docker-compose -f docker-compose.yml ps "sut" | grep "Exit 0"
  # Test containers can be dropped and restarted
  - docker-compose -f docker-compose.yml down
  - travis_retry docker-compose -f docker-compose.yml up -d etherpad_db && sleep 60
  - docker-compose -f docker-compose.yml ps
  - docker-compose -f docker-compose.yml logs "etherpad_db"
  - docker-compose -f docker-compose.yml ps "etherpad_db" | grep "Up"
  - travis_retry docker-compose -f docker-compose.yml up -d && sleep 30
  - docker-compose -f docker-compose.yml ps
  - docker-compose -f docker-compose.yml ps "etherpad" | grep "Up"
  - echo 'Wait until containers init and tests are over' && sleep 60
  - docker-compose -f docker-compose.yml logs "sut"
  - docker-compose -f docker-compose.yml ps "sut" | grep "Exit 0"

notifications:
  email: false

env: # Environments
    - VERSION=develop VARIANT=alpine
    - VERSION=develop VARIANT=debian
    - VERSION=1.8.0 VARIANT=alpine
    - VERSION=1.8.0 VARIANT=debian
