version: "2"

services:
  # https://docs.docker.com/docker-hub/builds/automated-testing/
  sut:
    build:
      context: ./test
      dockerfile: Dockerfile
    depends_on:
      - etherpad_db
      - etherpad
    volumes_from:
      - etherpad
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro

  etherpad:
    # For development or CI, tag build from local Dockerfile
    build:
      context: ./
      dockerfile: Dockerfile
      args: 
        - TAG=${TAG}
        - VCS_REF=${VCS_REF}
        - BUILD_DATE=${BUILD_DATE}
    # For production, download prebuilt image
    #image: ${IMAGE_NAME}
    container_name: etherpad
    #restart: always
    depends_on:
      - etherpad_db
    links:
      - etherpad_db
    #ports:
    #  - 9000:9000
    volumes:
      - /srv/etherpad/html:/var/www/html
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - DB_TYPE=postgres
      - DB_HOST=etherpad_db # same as pgsql container name
      - DB_PORT=5432
      - DB_NAME=${ETHERPAD_DB_NAME}
      - DB_USER=${ETHERPAD_DB_USER}
      - DB_PASS=${ETHERPAD_DB_PASSWORD}

  etherpad_db:
    image: postgres:latest
    container_name: etherpad_db
    restart: always
    #ports:
    #  - 5432:5432
    volumes:
      - /srv/etherpad/db:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - POSTGRES_DB=${ETHERPAD_DB_NAME}
      - POSTGRES_USER=${ETHERPAD_DB_USER}
      - POSTGRES_PASSWORD=${ETHERPAD_DB_PASSWORD}
